# Generated by Django 6.0.2 on 2026-03-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='package_interest',
            new_name='event_type',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='message',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='backdrop',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='booth_hours',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='bundle_packages',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='contact_person',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='custom_designs_branding',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='event_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='indoors_or_outdoors',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='prints_or_digital',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='props',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='spot',
            field=models.CharField(default='', max_length=200),
        ),
    ]
